AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  db

Globals:
  Function:
    Timeout: 10
    MemorySize: 128

Resources:
  DBFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: db/
      Handler: index.handler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      VpcConfig:
        SecurityGroupIds:
          - sg-abc
        SubnetIds:
          - subnet-xyz
      Environment:
        Variables:
          CONNECTION_STRING: "your_connection_string_here"
      Policies:
        - AWSLambdaVPCAccessExecutionRole